In [3]:
import numpy as np #Traer librería y utilizar como np

In [4]:
n=[1,2,3]

In [5]:
type(n)

list

In [6]:
m=np.array(n) #Transforma lista en array

In [7]:
type(m)

numpy.ndarray

In [8]:
m

array([1, 2, 3])

In [9]:
m.ndim #Dimensión en filas

1

In [10]:
m.shape #Dimensiones

(3,)

In [11]:
m=[1,2,3]
n=[3,4,5]

In [12]:
z=m+n

In [13]:
a=np.array(m)
a

array([1, 2, 3])

In [14]:
np.square(a) #Cuadrado de cada elemento

array([1, 4, 9], dtype=int32)

In [15]:
b=np.array([5,6,7])

In [16]:
z

[1, 2, 3, 3, 4, 5]

In [17]:
z[0]

1

In [18]:
z[-1]

5

In [19]:
b[0]

5

In [20]:
b[-1]

7

In [21]:
b[1]='letra'

ValueError: invalid literal for int() with base 10: 'letra'

In [22]:
b[1]=10

In [23]:
b

array([ 5, 10,  7])

In [24]:
c=a+b
c

array([ 6, 12, 10])

In [25]:
a

array([1, 2, 3])

In [26]:
a-1

array([0, 1, 2])

In [27]:
np.absolute(a) #Valor absoluto

array([1, 2, 3])

In [28]:
np.maximum([1, 2, 3, 12, 14, 15],[7, 8, 3, 3, 4, 5]) #Max de cada posición

array([ 7,  8,  3, 12, 14, 15])

In [29]:
np.minimum([1, 2, 3, 12, 14, 15],[7, 8, 3, 3, 4, 5])

array([1, 2, 3, 3, 4, 5])

In [30]:
d=np.array([17, 27, 35, 12, 14, 15])

In [31]:
d.sort()

In [32]:
d

array([12, 14, 15, 17, 27, 35])

In [33]:
np.insert(d,0,5,axis=0)

array([ 5, 12, 14, 15, 17, 27, 35])

In [34]:
np.append(a,b)

array([ 1,  2,  3,  5, 10,  7])

In [35]:
np.concatenate((a,b),axis=0)

array([ 1,  2,  3,  5, 10,  7])

In [36]:
e=np.array(range(3,31))

In [37]:
e

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
f=np.array([0,1,2,3,4,0,1,2,3,4])

In [39]:
f.sort()
f

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [40]:
g=np.array([[1,2.03,3],[13,0.1,15.3]])
g

array([[ 1.  ,  2.03,  3.  ],
       [13.  ,  0.1 , 15.3 ]])

In [41]:
g.shape #Dimensiones mxn

(2, 3)

In [42]:
g.ndim #Dimension en filas

2

In [43]:
g[-1,-1]

15.3

In [44]:
np.resize(g,(10,10))

array([[ 1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  ,
        13.  ],
       [ 0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,
         2.03],
       [ 3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 ,
        15.3 ],
       [ 1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  ,
        13.  ],
       [ 0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,
         2.03],
       [ 3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 ,
        15.3 ],
       [ 1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  ,
        13.  ],
       [ 0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,
         2.03],
       [ 3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  , 13.  ,  0.1 ,
        15.3 ],
       [ 1.  ,  2.03,  3.  , 13.  ,  0.1 , 15.3 ,  1.  ,  2.03,  3.  ,
        13.  ]])

In [45]:
h=np.arange(1,10,2) #Crea array de 1 a 10 con saltos de 2
h

array([1, 3, 5, 7, 9])

In [46]:
i=np.arange(1,10)
i

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ii=np.array([i,i])
ii

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
j=np.reshape(np.array(range(1,26)),(5,5))
j

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
k=np.asarray([1,2,3]) #Crea arreglo desde la lista
k

array([1, 2, 3])

In [50]:
k.dtype

dtype('int32')

In [51]:
l=k.astype('complex64') #Cambia propiedad a complex64

In [52]:
l.dtype

dtype('complex64')

In [53]:
l

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [54]:
np.eye(2, dtype=int) #Crea array de 1s y 0s de n dimensiones

array([[1, 0],
       [0, 1]])

In [69]:
np.eye(2,3, k=1) #Crea array de 2x3 desplazando el 1 un lugar a la derecha

array([[0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(N=2,M=3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.zeros(3) #Arreglo en ceros

array([0., 0., 0.])

In [58]:
np.ones (shape=(2,3)) #Arreglo en 1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.empty(shape=(3,3)) #Arreglo vacío

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.64e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [60]:
np.full(shape=(2,3), fill_value=False) #Arreglo con valor definido

array([[False, False, False],
       [False, False, False]])

In [61]:
np.identity(3) #Matriz identidad de dimensión n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
o=np.array(range(0,9))

In [63]:
p=np.reshape(o,(3,3))
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])