Operadores y operaciones

In [2]:
a=1
a

1

In [7]:
b=2
b

2

In [8]:
b **=3 #Eleva al exponente y reescribe variable
b

8

In [9]:
b *=10 #Multiplica por valor y reescibe la variable
b

80

In [11]:
b +=1 #Suma y reescribe
b

81

In [12]:
b -=1 #Resta y reescribe
b

80

In [13]:
b /=10 #Divide y reescribe
b

8.0

In [14]:
b //=3 #Divide en entero
b

2.0

In [15]:
c = 1

In [16]:
c = c+1
c

2

In [17]:
c += 1
c

3

In [18]:
d=7

In [19]:
d %= 2
d

1

In [1]:
1==2 #Evalúa igualdad

False

In [2]:
1>2 #Evalúa relación >,<,>=,<=

False

In [3]:
1!=2 #Evalúa diferencia 

True

In [4]:
cadena1,cadena2='Hola','Adiós'
lista1,lista2=[3,'Bienvenido',47],[2,'Lista2']

In [9]:
cadenas= cadena1==cadena2
listas= lista1==lista2
print(cadenas)
print(listas)

False
False


In [10]:
cadenas

False

In [11]:
cadena1

'Hola'

In [12]:
cadena2

'Adiós'

In [13]:
listas

False

In [14]:
lista1

[3, 'Bienvenido', 47]

In [15]:
lista2

[2, 'Lista2']

In [17]:
a,b,c='Hola','Mundo',' '

In [18]:
a

'Hola'

In [19]:
b

'Mundo'

In [20]:
c

' '

In [21]:
a+c+b

'Hola Mundo'

In [22]:
a*3+c+b

'HolaHolaHola Mundo'

In [23]:
d='Murciélago'

In [25]:
d[6:10]

'lago'

In [26]:
e=d[6:10]

In [27]:
e==d

False

In [28]:
e!=d

True

In [29]:
edad=24/2

In [33]:
print('Mi edad es',edad)

Mi edad es 12.0


In [34]:
#1/3 x - 15 = 6
x=(6+15)/(1/3)
print('La edad de mi hermana es',x)

La edad de mi hermana es 63.0


Máscaras

In [36]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
mascara = a>3

In [38]:
mascara

array([False, False, False,  True,  True,  True,  True])

In [39]:
mascara = a==3

In [40]:
mascara

array([False, False,  True, False, False, False, False])