# Instalar librerías

In [1]:
!pip install numpy

# Importar librerías a utilizar en este libro

In [2]:
import numpy

In [3]:
lista=[1,2,3]

In [4]:
type(lista)

list

Crear una matriz a partir de una lista (unidimensional)

In [5]:
matriz=numpy.array(lista) #Forma uno de crear una matriz

In [6]:
type(matriz)

numpy.ndarray

In [7]:
matriz

array([1, 2, 3])

In [8]:
import numpy as np

In [9]:
matriz2=np.array(lista)

In [10]:
matriz2

array([1, 2, 3])

In [11]:
matriz.ndim

1

In [12]:
matriz.shape

(3,)

In [13]:
lista3=[1.0,True,"a",3]

In [14]:
matriz3=np.array(lista3)

In [15]:
matriz3

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [16]:
print(matriz3.dtype)

<U32


In [17]:
print(matriz2.dtype)

int32


## Las matrices sólo pueden tener un tipo de dato

In [18]:
matriz4=np.array([1,2,3], dtype="float") #Segunda manera de crear una matriz (Escribir dentro de np.array)

In [19]:
matriz4

array([1., 2., 3.])

In [20]:
matriz4.dtype

dtype('float64')

In [21]:
matriz5=np.array([1,2,3], dtype="float16")

In [22]:
matriz5.dtype

dtype('float16')

# Operaciones con matrices

## Crear listas

In [23]:
m=[1,2,3]
n=[3,4,5]

In [24]:
m+n #Al sumar dos listas las coloca una detrás de otra

[1, 2, 3, 3, 4, 5]

In [25]:
matriz_m=np.array(m)
matriz_n=np.array(n)

In [26]:
matriz_m+matriz_n

array([4, 6, 8])

In [27]:
# Matriz tiene índices [a,b,c]

In [28]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [29]:
matriz_m[0]

1

In [30]:
matriz_m[-1]

3

In [31]:
matriz_m[-3]

1

In [32]:
matriz_m[0] = True

In [33]:
matriz_m

array([1, 2, 3])

In [34]:
matriz_m[1] = True

In [35]:
matriz_m

array([1, 1, 3])

In [36]:
matriz_m[0]= "abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [38]:
matriz_o=np.array([6,7,8,9])

In [39]:
matriz_o

array([6, 7, 8, 9])

In [40]:
matriz_m

array([1, 1, 3])

In [41]:
matriz_m+matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [44]:
matriz_negativos=matriz_m-matriz_n

In [45]:
np.absolute(matriz_negativos)

array([2, 3, 2])

In [46]:
np.maximum(matriz_m,matriz_n)

array([3, 4, 5])

In [47]:
np.minimum(matriz_m,matriz_n)

array([1, 1, 3])

In [48]:
np.maximum(matriz_m,matriz_o)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [49]:
matriz_m

array([1, 1, 3])

In [51]:
matriz_m.sort()
matriz_m

array([1, 1, 3])

In [58]:
matriz_m.sort()
matriz_m

TypeError: 'reversed' is an invalid keyword argument for this function